# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YFDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YFDemo

pod 'SDWebImage'
pod 'Masonry'
pod 'FMDB'
pod 'MBProgressHUD'
pod 'MJExtension', '~> 3.0.13'
pod 'AFNetworking'
pod 'FMDBHelpers'

end
